### ISSUE TITLE
Port xstream#tween to @cycle/time

### ISSUE THREAD

**Issue by Widdershin** [cyclejs/time#13]
Tween is the only time based operator in xstream that `@cycle/time` does not implement.

**Comment by Widdershin** [comment]
I don't want to include `tween` in core right now, because I think the current API surface is quite large. I want to support extra operators, so that we can provide niche operators without requiring people to bundle them.

This could look like:
```js
import {makeTimeDriver, mockTimeSource} from '@cycle/time';
import tween from '@cycle/time/extra/tween';

const drivers = {
  Time: makeTimeDriver({extra: {tween}})
}

const mockTime = mockTimeSource({extra: {tween}});
```

This will also open the way up to custom operators from users.

**Comment by staltz** [comment]
Also, I'm not sure tween() is the best way for doing animations. I used it in matrixmultiplication.xyz and in Firefox I still get some glitches, and I have no idea yet why how the glitch happens.

**Comment by staltz** [comment]
PS: Ben Lesh's recent talk on animations in RxJS using rAF might be relevant as an inspiration or reference. https://www.youtube.com/watch?v=X_RnO7KSR-4 You might know most of this so it's okay to watch it in 2x.
