### ISSUE TITLE
Support Jasmine's done.fail()

### ISSUE THREAD

**Issue by rjkip** [cyclejs/time#14]
Currently, the mock time source [passes](https://github.com/cyclejs/time/blob/f033b6e509143a04eb0b0e9dfe3c806c80fbcd01/src/mock-time-source.ts#L41) the combined assertion errors as an argument to `done`. This causes the test to pass when using Jasmine 2 (default for Jest), because Jasmine [has](https://jasmine.github.io/2.5/introduction.html#section-58) a separate `done.fail` function. Would you be interested in checking for the existence of and passing to error to `done.fail` before trying to pass the error to `done`? I can also submit a PR myself if you're short on time :)

**Comment by Widdershin** [comment]
Fixed by 2a3adf6 and released in v0.7.0.

`@cycle/time` will now call `done.fail` if it's present on `done` in the event of a failure.

Thanks for your issue. Can you test it out and verify that it works for your case and let me know how it goes?

**Comment by rjkip** [comment]
Jeez, you're quick. Looks good! I'll have to verify this later today :wink:

**Comment by rjkip** [comment]
All green here! :ok_hand:
