### ISSUE TITLE
Support snapshot style testing with html-looks-like

### ISSUE THREAD

**Issue by Widdershin** [cyclejs/time#19]
@staltz's new `html-looks-like` library looks like a lot of fun.

I want to be able to use it with @cycle/time.

https://github.com/staltz/html-looks-like

In order to do this, we might need to support custom assertion functions. This is probably an overall positive step for flexibility, and brings us more in line with how RxJS works.

Here's an example of what usage might look like:

```js
import {mockDOMSource, makeHTMLDriver} from '@cycle/dom';
import htmlLooksLike from 'html-looks-like';

import {Counter} from '../src/counter';

const htmlDriver = makeHTMLDriver();

function toHTML (vtree$) {
  return htmlDriver(vtree$).elements();
}

describe('Counter', () => {
  it('increments and decrements in response to clicks', (done) => {
    const Time = mockTimeSource();

    const expectedHTML = (count) => `
      <div class="counter">
        {{ ... }}
        <div class="count">Count: ${count}</div>
        {{ ... }}
      </div>
    `;

    const addClick$      = Time.diagram(`---x--x-------x--x--|`);
    const subtractClick$ = Time.diagram(`---------x----------|`);
    const expectedHTML$  = Time.diagram(`0--1--2--1----2--3--|`).map(expectedHTML);

    const DOM = mockDOMSource({
      '.add': {
        click: addClick$
      },

      '.subtract': {
        click: subtractClick$
      },
    });

    const counter = Counter({DOM});

    const HTML$ = counter.DOM.compose(toHTML);

    Time.assertEqual(HTML$, expectedHTML$, htmlLooksLike.bool)

    Time.run(done);
  });
});
```

**Comment by Widdershin** [comment]
If someone is interested in taking this on please comment and I will assign the issue to you 😸

**Comment by staltz** [comment]
```js
const expectedHTML = (count) => `
      <div class="counter">
        {{ ... }}
        <div class="count">Count: ${count}</div>
        {{ ... }}
      </div>
    `;
```

I haven't foreseen this type of usage. Amazing!

**Comment by chadrien** [comment]
That's an amazing feature! Should I PR the README so that one does not have to go to a closed issue to have an example of how this works? :)

**Comment by Widdershin** [comment]
There is an example in the README of custom equality operators but if you
want to document how this can be used for snapshot testing that would be
great.

**Comment by Widdershin** [comment]
Or we can move the example into the README, @raquelxmoss and I considered that but felt that it's a bit lengthy for an introduction.

If people think it would be a worthwhile addition to the README we can do that.

Also, once @cycle/time is in the monorepo with a nice table of contents it won't matter as much if the README is quite long, because there's a nice table of contents.

**Comment by chadrien** [comment]
Moving the example to the README is a pretty good idea imho. It needs a bit of update, as `makeHTMLDriver` has been moved to `@cycle/html`, but it would be just fine :ok_hand:

It's simple, straightforward, and really makes you want to try it (at least it worked on me)

**Comment by Widdershin** [comment]
We should really use `snabbdom-to-html` in the example instead since it's a bit simpler to set up, and once it's ready, `snabbdom-looks-like`.

If you want to make a pull request to put the example I would be in favour of that 😄

**Comment by chadrien** [comment]
That's a plan :)

**Comment by jvanbruegge** [comment]
for reference: https://github.com/cyclejs-community/create-cycle-app-flavors/blob/master/packages/cycle-scripts-one-fits-all/template/test/app.test.ts
