### ISSUE TITLE
Write a specification for the marble diagram DSL

### ISSUE THREAD

**Issue by Widdershin** [cyclejs/time#30]
As discussed in #16 it would be useful to have a document that fully specifies the behaviour of marble diagrams, possibly in a way that would allow us to unify the behaviour of RxJS and @cycle/time's diagrams.

This could be a markdown file in this repository or a separate repository altogether.

**Comment by staltz** [comment]
I've been intending to do this... I just a too large backlog in my life. Maybe we can hack on it in cycleconf? :)

**Comment by Widdershin** [comment]
Sounds good 👍

**Comment by Widdershin** [comment]
This issue was moved to cyclejs/cyclejs#763
