### ISSUE TITLE
cjs bundle means lodash deps for mocking are pulled in on production apps

### ISSUE THREAD

**Issue by willheslam** [cyclejs/time#40]
I wasn't sure if this issue should go here or in the main cyclejs repo - please let me know if I need to move it.

mock-time-source.ts uses package `combine-errors`, which [uses](https://github.com/matthewmueller/combine-errors/blob/master/index.js) package `lodash.uniqby` which then pulls in a bunch of extra lodash stuff which bloats the bundle considerably if you're not already using lodash.

lodash.uniqby brings in lodash.iteratee (56kb) among others - all in all it adds up to almost 100kb of extra code that won't be used: ![extralodashdeps](https://user-images.githubusercontent.com/5377213/28964261-ee9a1e98-7903-11e7-9581-c2cbee4fae85.png)

This wouldn't be a problem if we were able to use ES module versions of the packages (rather than bundled cjs) and a treeshaking/dead code eliminating bundler as in theory it could remove the unused modules.

My solution is to split the mock vs non-mock timesource files so in your tests you can pull in the mock time source (including any dependencies needed, e.g. lodash) but your app can pull in the skinnier time driver alone.
Here's an example:
https://github.com/cyclejs/time/compare/master...willheslam:separate-test-deps?expand=1

What do you think?

**Comment by jvanbruegge** [comment]
> This wouldn't be a problem if we were able to use ES module versions of the packages (rather than bundled cjs)

Why can't you use ES modules?

**Comment by willheslam** [comment]
If I `yarn add @cycle/time`, it installs the package compiled down to cjs.

eg. rxjs.js looks like
```
"use strict";
exports.__esModule = true;
var Observable_1 = require("rxjs/Observable");
require("rxjs/add/observable/from");
var adapt_1 = require("@cycle/run/lib/adapt");
var mock_time_source_1 = require("./dist/mock-time-source");
var time_driver_1 = require("./dist/time-driver");
adapt_1.setAdapt(function (stream) { return Observable_1.Observable.from(stream); });
function mockTimeSource(args) {
    return mock_time_source_1.mockTimeSource(args);
}
exports.mockTimeSource = mockTimeSource;
function timeDriver(_, adapter) {
    return time_driver_1.timeDriver(_, adapter);
}
exports.timeDriver = timeDriver;
```

Am I missing some yarn or npm command to pull in an ES module version?

(From my experience adding the package from github and trying to use the ts files directly (e.g. using tsloader and webpack) has never seemed to work well - maybe I should pull it in from github then try to compile it from typescript to an es module version before bundling?)

**Comment by Widdershin** [comment]
Ugh, good catch. Can you please open this over on the cyclejs repo, this repo is soon to be closed down? We definitely need to do something about this, and maybe set up a package size benchmark to prevent further unintentional bloat.

**Comment by willheslam** [comment]
Can do! @Widdershin https://github.com/cyclejs/cyclejs/issues/660
